# Read the documentation: https://github.com/FriendsOfSymfony/FOSElasticaBundle/blob/master/doc/setup.md
fos_elastica:
  clients:
    # default: { url: "%env(ELASTICSEARCH_URL)%" }
    default:
      host: "%fos_elastica.host%"
      port: "%fos_elastica.port%"
    # host: localhost
    # port: 8000

  indexes:
    app:
      # finder: ~
      client: default # Use the default client for the "app" index
      index_name: "search"
      # types:
      # post:
      # mappings:
      # properties:
      # id:
      # type: integer
      # user_id:
      # type: integer
      # title: ~
      # description: ~
      # owner_id:
      # type: integer
      # persistence:
      # driver: orm
      # model: AppBundle\Entity\Post
      #
#     search:
#       index_name: search
#       finder: ~
#       client: default
#       types:
#         post:
#           mappings:
#             id:
#               type: integer
#             user_id:
#               type: integer
#             title: ~
#             description: ~
#             owner_id:
#               type: integer
#           persistence:
#             driver: orm
#             model: AppBundle\Entity\Post
