version: "3"

services:
  ###> doctrine/doctrine-bundle ###
  database:
    image: postgres:${POSTGRES_VERSION:-15}-alpine
    environment:
      POSTGRES_DB: ${POSTGRES_DB:-app}
      # You should definitely change the password in production
      POSTGRES_PASSWORD: ${POSTGRES_PASSWORD:-!ChangeMe!}
      POSTGRES_USER: ${POSTGRES_USER:-app}
    volumes:
      - database_data:/var/lib/postgresql/data:rw
      # You may use a bind-mounted host directory instead, so that it is harder to accidentally remove the volume and lose all your data!
      # - ./docker/db/data:/var/lib/postgresql/data:rw
  ###< doctrine/doctrine-bundle ###

  elasticsearch:
    image: docker.elastic.co/elasticsearch/elasticsearch:7.9.3
    environment:
      - cluster.name=docker-cluster
      - bootstrap.memory_lock=true
      - discovery.type=single-node
      - "ES_JAVA_OPTS=-Xms512m -Xmx512m" # 512mo HEAP
    ulimits:
      memlock:
        soft: -1
        hard: -1
    ports:
      - 9200:9200

kibana:
  image: docker.elastic.co/kibana/kibana:7.9.3
  environment:
    ELASTICSEARCH_URL: http://elasticsearch:9200
  depends_on:
    - elasticsearch
  ports:
    - 5601:5601

volumes:
  ###> doctrine/doctrine-bundle ###
database_data:
  ###< doctrine/doctrine-bundle ###
